/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.jfedor.frozenbubble;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int bubble_1=0x7f020001;
        public static final int bubble_2=0x7f020002;
        public static final int bubble_3=0x7f020003;
        public static final int bubble_4=0x7f020004;
        public static final int bubble_5=0x7f020005;
        public static final int bubble_6=0x7f020006;
        public static final int bubble_7=0x7f020007;
        public static final int bubble_8=0x7f020008;
        public static final int bubble_blink=0x7f020009;
        public static final int bubble_colourblind_1=0x7f02000a;
        public static final int bubble_colourblind_2=0x7f02000b;
        public static final int bubble_colourblind_3=0x7f02000c;
        public static final int bubble_colourblind_4=0x7f02000d;
        public static final int bubble_colourblind_5=0x7f02000e;
        public static final int bubble_colourblind_6=0x7f02000f;
        public static final int bubble_colourblind_7=0x7f020010;
        public static final int bubble_colourblind_8=0x7f020011;
        public static final int bubble_font=0x7f020012;
        public static final int close_eyes=0x7f020013;
        public static final int compressor=0x7f020014;
        public static final int compressor_body=0x7f020015;
        public static final int fixed_1=0x7f020016;
        public static final int fixed_2=0x7f020017;
        public static final int fixed_3=0x7f020018;
        public static final int fixed_4=0x7f020019;
        public static final int fixed_5=0x7f02001a;
        public static final int fixed_6=0x7f02001b;
        public static final int frozen_1=0x7f02001c;
        public static final int frozen_2=0x7f02001d;
        public static final int frozen_3=0x7f02001e;
        public static final int frozen_4=0x7f02001f;
        public static final int frozen_5=0x7f020020;
        public static final int frozen_6=0x7f020021;
        public static final int frozen_7=0x7f020022;
        public static final int frozen_8=0x7f020023;
        public static final int hurry=0x7f020024;
        public static final int launcher=0x7f020025;
        public static final int life=0x7f020026;
        public static final int lose_panel=0x7f020027;
        public static final int penguins=0x7f020028;
        public static final int splash=0x7f020029;
        public static final int void_panel=0x7f02002a;
        public static final int win_panel=0x7f02002b;
    }
    public static final class id {
        public static final int game=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int applause=0x7f040000;
        public static final int destroy_group=0x7f040001;
        public static final int hurry=0x7f040002;
        public static final int launch=0x7f040003;
        public static final int lose=0x7f040004;
        public static final int newroot_solo=0x7f040005;
        public static final int noh=0x7f040006;
        public static final int rebound=0x7f040007;
        public static final int stick=0x7f040008;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int menu_about=0x7f050008;
        public static final int menu_colorblind_mode_off=0x7f050003;
        public static final int menu_colorblind_mode_on=0x7f050002;
        public static final int menu_dont_rush_me=0x7f050009;
        public static final int menu_fullscreen_off=0x7f050005;
        public static final int menu_fullscreen_on=0x7f050004;
        public static final int menu_new_game=0x7f050001;
        public static final int menu_rush_me=0x7f05000a;
        public static final int menu_sound_off=0x7f050007;
        public static final int menu_sound_on=0x7f050006;
    }
}
